[package]
name = "noptrex_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.0"
#polars = "0.22.8"

[profile.dev]
opt-level = 3
